twitter: "https://twitter.com/pritzoan"
github: "https://github.com/forestryio/prithvimp"
linkedin: "https://www.linkedin.com/in/prithvirajpillai/"
youtube: "http://www.youtube.com/channel/UCe80yKyxpQJXfORLleRy1EA"
dribbble: ""
instagram: "https://www.instagram.com/prithviraj_pillai/"
facebook: "https://www.facebook.com/prithviraj.pillai.77"
medium: "https://medium.com/@prithviMP"
patreon: ""
paypal: ""
unsplash: ""
